import { Book } from '../types'

export const books: Book[] = [
  {
    id: 1,
    title: '杀死一只知更鸟',
    author: '哈珀·李',
    isbn: '978-0061120084',
    publishYear: 1960,
    category: '小说',
    description: '这部令人难忘的小说描绘了美国南方小镇的童年生活，以及一场撼动整个社区的良知危机。通过孩子的视角深刻揭露了种族偏见与社会不公，展现了人性中的勇气与善良。',
    coverImage: 'https://images.pexels.com/photos/3747139/pexels-photo-3747139.jpeg?auto=compress&cs=tinysrgb&w=600  ',
    available: false,
    quantity: 3,
    borrowedBy: [2]
  },
  {
    id: 2,
    title: '一九八四',
    author: '乔治·奥威尔',
    isbn: '978-0451524935',
    publishYear: 1949,
    category: '小说',
    description: '这部反乌托邦经典设定在极权国家大洋国，描绘了永续战争、全方位监控与思想控制的恐怖世界。深刻警示权力滥用对自由的侵蚀，对人性异化与真理扭曲的剖析令人窒息。',
    coverImage: 'https://images.pexels.com/photos/3826686/pexels-photo-3826686.jpeg?auto=compress&cs=tinysrgb&w=600  ',
    available: true,
    quantity: 2,
    borrowedBy: []
  },
  {
    id: 3,
    title: '了不起的盖茨比',
    author: 'F·斯科特·菲茨杰拉德',
    isbn: '978-0743273565',
    publishYear: 1925,
    category: '名著',
    description: '这部关于浮华与幻灭的杰作精准捕捉了爵士时代美国社会的横截面。通过盖茨比对绿光的执着追寻，揭示了美国梦背后的阶级壁垒与人性虚妄，闪耀着诗意的悲剧光芒。',
    coverImage: 'https://images.pexels.com/photos/2465877/pexels-photo-2465877.jpeg?auto=compress&cs=tinysrgb&w=600  ',
    available: false,
    quantity: 1,
    borrowedBy: [2]
  },
  {
    id: 4,
    title: '傲慢与偏见',
    author: '简·奥斯汀',
    isbn: '978-0141439518',
    publishYear: 1813,
    category: '名著',
    description: '这部社会风俗喜剧通过伊丽莎白·班纳特的成长历程，犀利剖析了英国乡绅阶层的婚姻观与金钱观。充满机锋的对话与生动的人物塑造，使其成为爱情文学中不朽的范本。',
    coverImage: 'https://images.pexels.com/photos/1765033/pexels-photo-1765033.jpeg?auto=compress&cs=tinysrgb&w=600  ',
    available: true,
    quantity: 2,
    borrowedBy: []
  },
  {
    id: 5,
    title: '霍比特人',
    author: 'J·R·R·托尔金',
    isbn: '978-0547928227',
    publishYear: 1937,
    category: '奇幻',
    description: '这部中土世界冒险传奇讲述了平凡霍比特人比尔博·巴金斯的史诗征程。从袋底洞到孤山恶龙巢穴，在巫师与矮人同伴的陪伴下，他发现了超越想象的勇气与智慧。',
    coverImage: 'https://images.pexels.com/photos/2386687/pexels-photo-2386687.jpeg?auto=compress&cs=tinysrgb&w=600  ',
    available: false,
    quantity: 3,
    borrowedBy: [3]
  },
  {
    id: 6,
    title: '麦田里的守望者',
    author: 'J·D·塞林格',
    isbn: '978-0316769488',
    publishYear: 1951,
    category: '小说',
    description: '这部青春叛逆经典以霍尔顿·考尔菲德的口吻，赤裸展现青少年面对虚伪成人世界的疏离与挣扎。充满俚语的独白成为对抗社会异化的精神呐喊，引发全球代际共鸣。',
    coverImage: 'https://images.pexels.com/photos/2127790/pexels-photo-2127790.jpeg?auto=compress&cs=tinysrgb&w=600  ',
    available: true,
    quantity: 2,
    borrowedBy: []
  },
  {
    id: 7,
    title: '魔戒',
    author: 'J·R·R·托尔金',
    isbn: '978-0618640157',
    publishYear: 1954,
    category: '奇幻',
    description: '这部史诗级奇幻巨著构建了宏大的中土世界，围绕至尊魔戒展开正邪终极对决。从夏尔到魔多，弗罗多与护戒同盟的征程重新定义了勇气、友谊与牺牲的永恒价值。',
    coverImage: 'https://images.pexels.com/photos/1738805/pexels-photo-1738805.jpeg?auto=compress&cs=tinysrgb&w=600  ',
    available: true,
    quantity: 4,
    borrowedBy: []
  },
  {
    id: 8,
    title: '哈利·波特与魔法石',
    author: 'J·K·罗琳',
    isbn: '978-0747532699',
    publishYear: 1997,
    category: '奇幻',
    description: '这部现代奇幻开篇之作讲述孤儿哈利·波特在十一岁生日踏入霍格沃茨魔法学校的传奇。与赫敏、罗恩共同开启的魔法冒险，揭开了对抗黑魔王伏地魔的世纪之战序幕。',
    coverImage: 'https://images.pexels.com/photos/3388671/pexels-photo-3388671.jpeg?auto=compress&cs=tinysrgb&w=600  ',
    available: true,
    quantity: 5,
    borrowedBy: []
  },
   {
    id: 9,
    title: '三体',
    author: '刘慈欣',
    isbn: '978-7536692930',
    publishYear: 2008,
    category: '科幻',
    description: '地球文明与三体文明跨越四百年的宇宙史诗，黑暗森林法则震撼揭示宇宙社会学真相。人类在末日危机中挣扎求存，面壁计划与破壁人的智斗堪称科幻谋略巅峰之作。',
    coverImage: 'https://images.pexels.com/photos/414144/pexels-photo-414144.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: true,
    quantity: 4,
    borrowedBy: []
  },
  {
    id: 10,
    title: '活着',
    author: '余华',
    isbn: '978-7506365437',
    publishYear: 1993,
    category: '文学',
    description: '农民福贵历经内战、文革等时代巨变，亲人相继离世的苦难史诗。在绝望中展现生命的韧性，用平淡笔触书写最深沉的人性悲歌，堪称中国当代文学不朽经典。',
    coverImage: 'https://images.pexels.com/photos/159866/books-book-pages-read-literature-159866.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: false,
    quantity: 3,
    borrowedBy: [5]
  },
  {
    id: 11,
    title: '平凡的世界',
    author: '路遥',
    isbn: '978-7020049295',
    publishYear: 1986,
    category: '名著',
    description: '陕北农村孙少安、孙少平兄弟在改革开放浪潮中的奋斗史诗。通过两代人的命运浮沉，全景展现中国社会转型期城乡变迁，被誉为“茅盾文学奖皇冠上的明珠”。',
    coverImage: 'https://images.pexels.com/photos/1926988/pexels-photo-1926988.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: true,
    quantity: 5,
    borrowedBy: []
  },
  {
    id: 12,
    title: '白夜行',
    author: '东野圭吾',
    isbn: '978-7544258609',
    publishYear: 1999,
    category: '悬疑',
    description: '桐原亮司与唐泽雪穗在命案阴影下的共生关系，十九年连环罪案编织成绝望爱情罗网。精密的多线叙事揭开人性深渊，开创社会派推理新纪元。',
    coverImage: 'https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: true,
    quantity: 2,
    borrowedBy: []
  },
  {
    id: 13,
    title: '围城',
    author: '钱钟书',
    isbn: '978-7020024759',
    publishYear: 1947,
    category: '名著',
    description: '留洋博士方鸿渐在爱情与事业双重围城中的困顿人生。犀利剖析知识分子的虚伪与懦弱，警句“城外的人想冲进去，城里的人想逃出来”成为时代隐喻。',
    coverImage: 'https://images.pexels.com/photos/1319854/pexels-photo-1319854.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: false,
    quantity: 1,
    borrowedBy: [7]
  },
  {
    id: 14,
    title: '天龙八部',
    author: '金庸',
    isbn: '978-7805798233',
    publishYear: 1963,
    category: '武侠',
    description: '宋辽夏大理多国纷争背景下的江湖史诗，乔峰、虚竹、段誉三主角的命运交响。以佛家“八部天龙”隐喻众生相，将武侠提升至哲学境界的巅峰之作。',
    coverImage: 'https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: true,
    quantity: 3,
    borrowedBy: []
  },
  {
    id: 15,
    title: '撒哈拉的故事',
    author: '三毛',
    isbn: '978-7530216782',
    publishYear: 1976,
    category: '文学',
    description: '三毛与荷西在撒哈拉的流浪传奇，用炽热文字记录沙漠婚礼、悬壶济世的异域人生。自由灵魂与荒原的对话，开创华语旅行文学全新美学范式。',
    coverImage: 'https://images.pexels.com/photos/235986/pexels-photo-235986.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: true,
    quantity: 2,
    borrowedBy: []
  },
  {
    id: 16,
    title: '明朝那些事儿',
    author: '当年明月',
    isbn: '978-7801656087',
    publishYear: 2006,
    category: '历史',
    description: '以网络语言重述三百年明史，朱元璋到崇祯九帝的鲜活群像。打破正史叙事框架，用职场逻辑解构朝堂斗争，掀起全民读史新浪潮。',
    coverImage: 'https://images.pexels.com/photos/459791/pexels-photo-459791.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: false,
    quantity: 4,
    borrowedBy: [1,3]
  },
  {
    id: 17,
    title: '台北人',
    author: '白先勇',
    isbn: '978-9573305540',
    publishYear: 1971,
    category: '小说',
    description: '十四篇离散者的台北浮世绘，从将军遗孀到酒家女，承载民国记忆的流亡者群像。融古典诗词意境于现代叙事，奠定华语世纪末文学美学典范。',
    coverImage: 'https://images.pexels.com/photos/3631711/pexels-photo-3631711.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: true,
    quantity: 3,
    borrowedBy: []
  },
  {
    id: 18,
    title: '孽子',
    author: '白先勇',
    isbn: '978-9573308961',
    publishYear: 1983,
    category: '文学',
    description: '台北新公园“黑暗王国”中青春鸟们的爱欲挣扎，被家庭放逐的同性恋少年寻找救赎。以父权冲突隐喻家国认同，开创华语酷儿文学先河。',
    coverImage: 'https://images.pexels.com/photos/1370296/pexels-photo-1370296.jpeg?auto=compress&cs=tinysrgb&w=600',
    available: true,
    quantity: 2,
    borrowedBy: []
  }
]

export default books